/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "Bridge.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Color, Color, AUTO)


PB_BIND(RotationXY, RotationXY, AUTO)


PB_BIND(DataFrameRequest, DataFrameRequest, AUTO)


PB_BIND(DataFrameResponse, DataFrameResponse, AUTO)





